using System;
using ClassLibrary;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class _1_DataEntry : System.Web.UI.Page
{

    protected void btnOK_Click(object sender, EventArgs e)
    {
        clsCustomer ACustomer = new clsCustomer();

        // 1. Capture UI data
        string FirstName = txtFirstName.Text;
        string LastName = txtLastName.Text;
        string Email = txtEmail.Text;
        string DateJoinedText = txtDateJoined.Text;

        // 2. Validate Customer Data
        string Error = ACustomer.Valid(FirstName, LastName, Email, DateJoinedText);

        // *Optional*: You should also validate the Address textboxes here using your AnAddress.Valid() method before proceeding

        if (Error == "")
        {
            ACustomer.CustomerNo = CustomerNo;
            ACustomer.FirstName = FirstName;
            ACustomer.LastName = LastName;
            ACustomer.Email = Email;
            ACustomer.DateJoined = Convert.ToDateTime(DateJoinedText);
            ACustomer.IsActiveAccount = chkIsActiveAccount.Checked;

            clsCustomerCollection CustomerList = new clsCustomerCollection();

            // IF NEW RECORD
            if (CustomerNo == -1)
            {
                CustomerList.ThisCustomer = ACustomer;

                // 3. Save the Customer first
                CustomerList.Add();

                // 4. Get the new CustomerNo generated by SQL Server
                int newlyCreatedCustomerNo = GetLastInsertedCustomerNo();

                // 5. Instantly create and save the Address linking to this new customer
                clsAddressCollection AddressList = new clsAddressCollection();
                clsAddress AnAddress = new clsAddress();

                AnAddress.CustomerNo = newlyCreatedCustomerNo;
                AnAddress.Emirate = txtEmirate.Text;
                AnAddress.BuildingName = txtBuildingName.Text;
                AnAddress.StreetName = txtStreetName.Text;
                AnAddress.AddressType = txtAddressType.Text;
                AnAddress.Postcode = Convert.ToInt32(txtPostcode.Text); // Ensure you handle empty textboxes if postcode isn't mandatory!
                AnAddress.IsDefault = true; // Auto-set their first address as default

                AddressList.ThisAddress = AnAddress;
                AddressList.Add();
            }
            // IF UPDATING RECORD
            else
            {
                CustomerList.ThisCustomer.Find(CustomerNo);
                CustomerList.ThisCustomer = ACustomer;
                CustomerList.Update();

                // Note: If updating a customer, you usually handle updating their address via the AddressList page, 
                // so we skip AddressList.Update() here unless you want to load and overwrite it.
            }

            Response.Redirect("CustomerList.aspx");
        }
        else
        {
            lblError.Text = Error;
        }
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("CustomerList.aspx");
    }

    protected void btnFind_Click(object sender, EventArgs e)
    {
        clsCustomer AnCustomer = new clsCustomer();
        Int32 CustomerNo;
        Boolean Found = false;

        if (txtCustomerNo.Text != "")
        {
            CustomerNo = Convert.ToInt32(txtCustomerNo.Text);
            Found = AnCustomer.Find(CustomerNo);
           
            if (Found == true)
            {
                txtCustomerNo.Text = AnCustomer.CustomerNo.ToString();
                txtFirstName.Text = AnCustomer.FirstName.ToString();
                txtLastName.Text = AnCustomer.LastName.ToString();
                txtDateJoined.Text = AnCustomer.DateJoined.ToString();
                txtEmail.Text = AnCustomer.Email.ToString();
                chkIsActiveAccount.Checked = AnCustomer.IsActiveAccount;
                lblError.Text = "";
            }
            else { lblError.Text = "Customer not found."; }
        }
    }

    //variable to store the primary key with page level scope
    Int32 CustomerNo;

    protected void Page_Load(object sender, EventArgs e)
    {
        // Get the number of the customer to be processed
        CustomerNo = Convert.ToInt32(Session["CustomerNo"]);

        if (IsPostBack == false)
        {
            // If this is not a new record
            if (CustomerNo != -1)
            {
                // Display the current data for the record
                DisplayCustomer();
            }
            else
            {
                // IT IS A NEW RECORD
                // Autofill the text box with the predicted next ID
                txtCustomerNo.Text = GetExpectedNextID().ToString();

                // Note: We do NOT set ReadOnly = true. 
                // The user can clear this number and use the Find button if they want.
            }
        }
    }

    private int GetExpectedNextID()
    {
        int nextId = 1;

        // Hardcoding your exact Azure SQL connection string directly into the variable
        string connectionString = "Data Source=bald-gingers.database.windows.net; Initial Catalog=bald-gingers; User ID=baldgingers; Password=Atifgiveme@password; Connect Timeout=30; Encrypt=False; TrustServerCertificate=False; ApplicationIntent=ReadWrite; MultiSubnetFailover=False";

        using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connectionString))
        {
            string query = "SELECT IDENT_CURRENT('tblCustomer') + IDENT_INCR('tblCustomer')";

            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
            {
                conn.Open();
                object result = cmd.ExecuteScalar();

                if (result != DBNull.Value && result != null)
                {
                    nextId = Convert.ToInt32(result);
                }
            }
        }
        return nextId;
    }

    private int GetLastInsertedCustomerNo()
    {
        int lastId = 0;
        // Ensure this matches your Web.config connection string name
        string connectionString = "Data Source=bald-gingers.database.windows.net; Initial Catalog=bald-gingers; User ID=baldgingers; Password=Atifgiveme@password; Connect Timeout=30; Encrypt=False; TrustServerCertificate=False; ApplicationIntent=ReadWrite; MultiSubnetFailover=False";

        using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connectionString))
        {
            // IDENT_CURRENT gets the exact ID of the row we just inserted into tblCustomer
            string query = "SELECT IDENT_CURRENT('tblCustomer')";

            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
            {
                conn.Open();
                object result = cmd.ExecuteScalar();
                if (result != DBNull.Value && result != null)
                {
                    lastId = Convert.ToInt32(result);
                }
            }
        }
        return lastId;
    }

    // Method to fetch the existing record and fill the text boxes
    void DisplayCustomer()
    {
        //create an instance of the customer collection
        clsCustomerCollection CustomerBook = new clsCustomerCollection();

        //find the record to update
        CustomerBook.ThisCustomer.Find(CustomerNo);

        //display the data for this record inside the text boxes
        txtCustomerNo.Text = CustomerBook.ThisCustomer.CustomerNo.ToString();
        txtFirstName.Text = CustomerBook.ThisCustomer.FirstName;
        txtLastName.Text = CustomerBook.ThisCustomer.LastName;
        txtEmail.Text = CustomerBook.ThisCustomer.Email;
        // Format the date so it looks nice in the text box
        txtDateJoined.Text = CustomerBook.ThisCustomer.DateJoined.ToString("dd/MM/yyyy");
        chkIsActiveAccount.Checked = CustomerBook.ThisCustomer.IsActiveAccount;
    }

    protected void btnReturn_Click(object sender, EventArgs e)
    {
        // Redirect to the Admin Menu page
        Response.Redirect("TeamMainMenu.aspx");
    }


}