using System;
using ClassLibrary;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class _1_DataEntry : System.Web.UI.Page
{

    protected void btnOK_Click(object sender, EventArgs e)
    {
        clsCustomer ACustomer = new clsCustomer();

        // 1. Capture UI data
        string FirstName = txtFirstName.Text;
        string LastName = txtLastName.Text;
        string Email = txtEmail.Text;
        string DateJoinedText = txtDateJoined.Text;

        // 2. Validate Customer Data
        string Error = ACustomer.Valid(FirstName, LastName, Email, DateJoinedText);

        // *Optional*: You should also validate the Address textboxes here using your AnAddress.Valid() method before proceeding

        if (Error == "")
        {
            ACustomer.CustomerNo = CustomerNo;
            ACustomer.FirstName = FirstName;
            ACustomer.LastName = LastName;
            ACustomer.Email = Email;
            ACustomer.DateJoined = Convert.ToDateTime(DateJoinedText);
            ACustomer.IsActiveAccount = chkIsActiveAccount.Checked;

            clsCustomerCollection CustomerList = new clsCustomerCollection();

            // IF NEW RECORD
            if (CustomerNo == -1)
            {
                CustomerList.ThisCustomer = ACustomer;

                // 3. Save the Customer first
                CustomerList.Add();

                // 4. Get the new CustomerNo generated by SQL Server
                int newlyCreatedCustomerNo = GetLastInsertedCustomerNo();

                // 5. Instantly create and save the Address linking to this new customer
                clsAddressCollection AddressList = new clsAddressCollection();
                clsAddress AnAddress = new clsAddress();

                AnAddress.CustomerNo = newlyCreatedCustomerNo;
                AnAddress.Emirate = txtEmirate.Text;
                AnAddress.BuildingName = txtBuildingName.Text;
                AnAddress.StreetName = txtStreetName.Text;
                AnAddress.AddressType = txtAddressType.Text;
                AnAddress.Postcode = Convert.ToInt32(txtPostcode.Text); // Ensure you handle empty textboxes if postcode isn't mandatory!
                AnAddress.IsDefault = true; // Auto-set their first address as default

                AddressList.ThisAddress = AnAddress;
                AddressList.Add();
            }
            // IF UPDATING RECORD
            else
            {
                CustomerList.ThisCustomer.Find(CustomerNo);
                CustomerList.ThisCustomer = ACustomer;
                CustomerList.Update();
                if (ViewState["AddingExtraAddress"] != null && (bool)ViewState["AddingExtraAddress"] == true)
                {
                    clsAddressCollection AddressList = new clsAddressCollection();
                    clsAddress ExtraAddress = new clsAddress();

                    ExtraAddress.CustomerNo = CustomerNo; // Link to the current customer
                    ExtraAddress.Emirate = txtEmirate.Text;
                    ExtraAddress.BuildingName = txtBuildingName.Text;
                    ExtraAddress.StreetName = txtStreetName.Text;
                    ExtraAddress.AddressType = txtAddressType.Text;
                    ExtraAddress.Postcode = Convert.ToInt32(txtPostcode.Text);
                    ExtraAddress.IsDefault = false; // Extra addresses are usually not default

                    AddressList.ThisAddress = ExtraAddress;
                    AddressList.Add();

                }
            }

                Response.Redirect("CustomerList.aspx");
            }
        else
            {
                lblError.Text = Error;
            }
        }
    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("CustomerList.aspx");
    }

    protected void btnFind_Click(object sender, EventArgs e)
    {
        clsCustomer AnCustomer = new clsCustomer();
        Int32 CustomerNo;
        Boolean Found = false;

        if (txtCustomerNo.Text != "")
        {
            CustomerNo = Convert.ToInt32(txtCustomerNo.Text);
            Found = AnCustomer.Find(CustomerNo);
           
            if (Found == true)
            {
                txtCustomerNo.Text = AnCustomer.CustomerNo.ToString();
                txtFirstName.Text = AnCustomer.FirstName.ToString();
                txtLastName.Text = AnCustomer.LastName.ToString();
                txtDateJoined.Text = AnCustomer.DateJoined.ToString();
                txtEmail.Text = AnCustomer.Email.ToString();
                chkIsActiveAccount.Checked = AnCustomer.IsActiveAccount;
                lblError.Text = "";
            }
            else { lblError.Text = "Customer not found."; }
        }
    }

    //variable to store the primary key with page level scope
    Int32 CustomerNo;

    protected void Page_Load(object sender, EventArgs e)
    {
        CustomerNo = Convert.ToInt32(Session["CustomerNo"]);

        if (IsPostBack == false)
        {
            if (CustomerNo != -1)
            {
                DisplayCustomer();
                LoadAddressDropdown(CustomerNo); // Loads the dropdown
            }
            else
            {
                // Brand new customer: Hide the dropdown and extra button
                txtCustomerNo.Text = GetExpectedNextID().ToString();
                divAddressDropdown.Visible = false;
                btnPrepareNewAddress.Visible = false;
            }
        }
    }

    private int GetExpectedNextID()
    {
        int nextId = 1;

        // Hardcoding your exact Azure SQL connection string directly into the variable
        string connectionString = "Data Source=bald-gingers.database.windows.net; Initial Catalog=bald-gingers; User ID=baldgingers; Password=Atifgiveme@password; Connect Timeout=30; Encrypt=False; TrustServerCertificate=False; ApplicationIntent=ReadWrite; MultiSubnetFailover=False";

        using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connectionString))
        {
            string query = "SELECT IDENT_CURRENT('tblCustomer') + IDENT_INCR('tblCustomer')";

            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
            {
                conn.Open();
                object result = cmd.ExecuteScalar();

                if (result != DBNull.Value && result != null)
                {
                    nextId = Convert.ToInt32(result);
                }
            }
        }
        return nextId;
    }

    private int GetLastInsertedCustomerNo()
    {
        int lastId = 0;
        // Ensure this matches your Web.config connection string name
        string connectionString = "Data Source=bald-gingers.database.windows.net; Initial Catalog=bald-gingers; User ID=baldgingers; Password=Atifgiveme@password; Connect Timeout=30; Encrypt=False; TrustServerCertificate=False; ApplicationIntent=ReadWrite; MultiSubnetFailover=False";

        using (System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connectionString))
        {
            // IDENT_CURRENT gets the exact ID of the row we just inserted into tblCustomer
            string query = "SELECT IDENT_CURRENT('tblCustomer')";

            using (System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn))
            {
                conn.Open();
                object result = cmd.ExecuteScalar();
                if (result != DBNull.Value && result != null)
                {
                    lastId = Convert.ToInt32(result);
                }
            }
        }
        return lastId;
    }

    // Method to fetch the existing record and fill the text boxes
    void DisplayCustomer()
    {
        //create an instance of the customer collection
        clsCustomerCollection CustomerBook = new clsCustomerCollection();

        //find the record to update
        CustomerBook.ThisCustomer.Find(CustomerNo);

        //display the data for this record inside the text boxes
        txtCustomerNo.Text = CustomerBook.ThisCustomer.CustomerNo.ToString();
        txtFirstName.Text = CustomerBook.ThisCustomer.FirstName;
        txtLastName.Text = CustomerBook.ThisCustomer.LastName;
        txtEmail.Text = CustomerBook.ThisCustomer.Email;
        // Format the date so it looks nice in the text box
        txtDateJoined.Text = CustomerBook.ThisCustomer.DateJoined.ToString("dd/MM/yyyy");
        chkIsActiveAccount.Checked = CustomerBook.ThisCustomer.IsActiveAccount;
    }

    void DisplayCustomerAddress(int currentCustomerNo)
    {
        // Create an instance of the address collection to search through
        clsAddressCollection Addresses = new clsAddressCollection();

        // Use LINQ to find the first address that belongs to this CustomerNo
        var customerAddress = Addresses.AddressList.FirstOrDefault(a => a.CustomerNo == currentCustomerNo);

        if (customerAddress != null)
        {
            // If an address is found, display the data
            txtEmirate.Text = customerAddress.Emirate;
            txtBuildingName.Text = customerAddress.BuildingName;
            txtStreetName.Text = customerAddress.StreetName;
            txtAddressType.Text = customerAddress.AddressType;
            txtPostcode.Text = customerAddress.Postcode.ToString();
        }
        else
        {
            // If no address is found (e.g., old test data), show a safe placeholder
            txtEmirate.Text = "N/A";
            txtBuildingName.Text = "N/A";
            txtStreetName.Text = "N/A";
            txtAddressType.Text = "N/A";
            txtPostcode.Text = "N/A";
        }

        // Lock all the text boxes so the user cannot type in them
        txtEmirate.ReadOnly = true;
        txtBuildingName.ReadOnly = true;
        txtStreetName.ReadOnly = true;
        txtAddressType.ReadOnly = true;
        txtPostcode.ReadOnly = true;

        // Visually grey them out using Bootstrap classes so the user knows they are locked
        txtEmirate.CssClass = "form-control bg-light text-muted";
        txtBuildingName.CssClass = "form-control bg-light text-muted";
        txtStreetName.CssClass = "form-control bg-light text-muted";
        txtAddressType.CssClass = "form-control bg-light text-muted";
        txtPostcode.CssClass = "form-control bg-light text-muted";
    }

    protected void btnReturn_Click(object sender, EventArgs e)
    {
        // Redirect to the Admin Menu page
        Response.Redirect("TeamMainMenu.aspx");
    }

    void LoadAddressDropdown(int currentCustomerNo)
    {
        clsAddressCollection Addresses = new clsAddressCollection();

        // Find ALL addresses linked to this customer
        var customerAddresses = Addresses.AddressList.Where(a => a.CustomerNo == currentCustomerNo).ToList();

        if (customerAddresses.Count > 0)
        {
            // Format a clean label for the dropdown (C# 5 compatible)
            var formattedList = customerAddresses.Select(a => new {
                AddressId = a.AddressId,
                DisplayText = string.Format("{0} - {1}, {2} (Postcode: {3})", a.AddressType, a.StreetName, a.Emirate, a.Postcode)
            }).ToList();

            ddlAddresses.DataSource = formattedList;
            ddlAddresses.DataValueField = "AddressId";
            ddlAddresses.DataTextField = "DisplayText";
            ddlAddresses.DataBind();

            // Load the first address into the locked boxes
            DisplaySelectedAddress(Convert.ToInt32(ddlAddresses.SelectedValue));
        }
        else
        {
            ddlAddresses.Items.Add(new ListItem("No Addresses Found", "-1"));
            ddlAddresses.Enabled = false;
        }
    }

    void DisplaySelectedAddress(int addressId)
    {
        clsAddressCollection Addresses = new clsAddressCollection();
        var address = Addresses.AddressList.FirstOrDefault(a => a.AddressId == addressId);

        if (address != null)
        {
            txtEmirate.Text = address.Emirate;
            txtBuildingName.Text = address.BuildingName;
            txtStreetName.Text = address.StreetName;
            txtAddressType.Text = address.AddressType;
            txtPostcode.Text = address.Postcode.ToString();

            // Lock them and grey them out
            txtEmirate.ReadOnly = true; txtEmirate.CssClass = "form-control bg-light text-muted";
            txtBuildingName.ReadOnly = true; txtBuildingName.CssClass = "form-control bg-light text-muted";
            txtStreetName.ReadOnly = true; txtStreetName.CssClass = "form-control bg-light text-muted";
            txtAddressType.ReadOnly = true; txtAddressType.CssClass = "form-control bg-light text-muted";
            txtPostcode.ReadOnly = true; txtPostcode.CssClass = "form-control bg-light text-muted";
        }
    }

    protected void ddlAddresses_SelectedIndexChanged(object sender, EventArgs e)
    {
        // When the user picks a different address from the dropdown, update the boxes
        int selectedId = Convert.ToInt32(ddlAddresses.SelectedValue);
        if (selectedId != -1)
        {
            DisplaySelectedAddress(selectedId);
            ViewState["AddingExtraAddress"] = false; // Cancel adding mode if they click the dropdown
        }
    }

    protected void btnPrepareNewAddress_Click(object sender, EventArgs e)
    {
        // Clear all boxes
        txtEmirate.Text = "";
        txtBuildingName.Text = "";
        txtStreetName.Text = "";
        txtAddressType.Text = ""; // User can type "Work" or "Holiday Home" here
        txtPostcode.Text = "";

        // Unlock boxes and make them white again
        txtEmirate.ReadOnly = false; txtEmirate.CssClass = "form-control border-success";
        txtBuildingName.ReadOnly = false; txtBuildingName.CssClass = "form-control border-success";
        txtStreetName.ReadOnly = false; txtStreetName.CssClass = "form-control border-success";
        txtAddressType.ReadOnly = false; txtAddressType.CssClass = "form-control border-success";
        txtPostcode.ReadOnly = false; txtPostcode.CssClass = "form-control border-success";

        // Tell the OK button that we are saving an extra address!
        ViewState["AddingExtraAddress"] = true;

        lblError.Text = "Please enter the new address details and click OK to save.";
        lblError.CssClass = "text-success fw-bold";
    }

}